backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

display_url: https://gatsby-netlify-cms-example.netlify.com/

collections:
  - name: "home"
    label: "Home page sections"
    description: "All home page sections, use key field to tie content to its component"
    folder: "markdown/home"
    create: true
    fields:
      - { label: "Key", name: "key", widget: "string" }
      - { label: "Heading", name: "heading", widget: "string" }
      - {
          label: "Image",
          name: "image",
          required: false,
          widget: "object",
          fields:
            [
              { label: "Image", name: "image", widget: "image" },
              {
                label: "Image Description",
                name: "imageAlt",
                widget: "string",
              },
            ],
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - {
          label: "Call to Actions",
          name: "callToActions",
          required: false,
          widget: "object",
          fields:
            [
              {
                label: "First CTA",
                name: "firstCTA",
                required: true,
                widget: "object",
                fields:
                  [
                    { label: "Heading", name: "heading", widget: "string" },
                    {
                      label: "Sub Heading",
                      name: "subHeading",
                      widget: "string",
                    },
                    {
                      label: "Link Type",
                      name: "linkType",
                      widget: "select",
                      options: ["internal", "external"],
                    },
                    {
                      label: "Link URL",
                      name: "linkURL",
                      widget: "string",
                      hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                    },
                  ],
              },
              {
                label: "Second CTA",
                name: "secondCTA",
                required: false,
                widget: "object",
                fields:
                  [
                    { label: "Heading", name: "heading", widget: "string" },
                    {
                      label: "Sub Heading",
                      name: "subHeading",
                      widget: "string",
                    },
                    {
                      label: "Link Type",
                      name: "linkType",
                      widget: "select",
                      options: ["internal", "external"],
                    },
                    {
                      label: "Link URL",
                      name: "linkURL",
                      widget: "string",
                      hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                    },
                  ],
              },
            ],
        }

      - file: "markdown/home/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "home-page",
            }
          - {
              label: "Header Image",
              name: "headerImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                ],
            }
          - { label: "Title", name: "title", widget: "string" }
          - {
              label: "Upcoming Meetup Heading",
              name: "upcomingMeetupHeading",
              widget: "string",
            }
          - {
              label: "No Upcoming Meetup Text",
              name: "noUpcomingMeetupText",
              hint: "This text will be displayed when there are no upcoming meetups",
              required: true,
              widget: "string",
            }
          - {
              label: "Maps Note",
              name: "mapsNote",
              required: true,
              widget: "string",
            }
          - {
              label: "SEO & Meta",
              name: "seo",
              widget: "object",
              fields:
                [
                  {
                    label: "Browser Tab Title",
                    name: "browserTitle",
                    widget: "string",
                  },
                  { label: "Title", name: "title", widget: "string" },
                  {
                    label: "Description",
                    name: "description",
                    widget: "string",
                  },
                ],
            }
  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "markdown/layout/navbar.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "navbar",
            }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["internal", "external"],
                  },
                  {
                    label: "Link URL",
                    name: "linkURL",
                    widget: "string",
                    hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                  },
                ],
            }
      - file: "markdown/layout/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "footer",
            }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }
