backend:
  name: github
  repo: Mirkotorrisi/casa-michele-cosentino
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: section
    label: Section
    folder: home/sections
    delete: false
    create: true
    fields:
      - { name: id, label: id, widget: string }
      - { name: h2, label: Heading, widget: string }
      - { name: body, label: Body, widget: markdown }
      - name: image_gallery
        label: Images
        widget: image
        choose_url: false
        media_folder: the-building/
        allow_multiple: true
        media_library:
          config:
            multiple: true
  - name: services
    label: Services
    folder: home/services
    widget: string
    create: true
    delete: false
    fields:
      - { name: title, label: Title, widget: string }
      - { name: subtitle, label: Subtitle, widget: string }
      - { name: image, label: Image, widget: image }
