backend:
  name: github
  repo: Mirkotorrisi/casa-michele-cosentino
  branch: master

media_folder: static/assets
public_folder: /assets

collections:
  - name: hero
    label: Hero Section
    folder: home/sections
    widget: "string"
    create: true
    delete: false
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
  - name: who-we-are
    label: Who We Are Section
    folder: home/sections
    widget: "string"
    create: true
    delete: false
    fields:
      - { name: title, label: Title, widget: "string" }
      - { name: subtitle, label: Subtitle, widget: "string" }
  - name: our-services
    label: Our services Section
    folder: home/sections
    widget: "string"
    create: true
    delete: false
    fields:
      - { name: title, label: Title }
      - { name: subtitle, label: Subtitle }
  - name: services
    label: Services
    folder: home/sections
    create: true
    fields:
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
