backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "vocabulary"
    label: "Vocabulary"
    description: "Every copy or single word, needs a unique key (preferred kebab-case) and a pageKey"
    files:
      - file: "markdown/vocabulary/home.md"
        label: "Home page Vocabulary"
        name: "homeVocabulary"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "home",
            }

          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/chi-siamo.md"
        label: "Chi siamo page Vocabulary"
        name: "chiSiamoVocabulary"
        pageKey: "chi-siamo"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "chi-siamo",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/servizi.md"
        label: "Servizi page Vocabulary"
        name: "serviziVocabulary"
        pageKey: "servizi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "servizi",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/feste-ed-eventi.md"
        label: "Feste ed eventi page Vocabulary"
        name: "festeEdEventiVocabulary"
        pageKey: "feste-ed-eventi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "feste-ed-eventi",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
  - name: "gallery"
    label: "Images"
    description: "Every image, needs a unique key (preferred kebab-case) and a pageKey"
    files:
      - file: "markdown/gallery/home.md"
        label: "Home page Gallery"
        name: "homeGallery"
        pageKey: "home"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "home",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/chi-siamo.md"
        label: "Chi siamo page Gallery"
        name: "chiSiamoGallery"
        pageKey: "chi-siamo"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "chi-siamo",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/servizi.md"
        label: "Servizi page Gallery"
        name: "serviziGallery"
        pageKey: "servizi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "servizi",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/feste-ed-eventi.md"
        label: "Feste ed eventi page Gallery"
        name: "festeEdEventiGallery"
        pageKey: "feste-ed-eventi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "feste-ed-eventi",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }

  - name: "navbarAndFooter"
    label: "Navbar & Footer"
    files:
      - file: "markdown/layout/navbar.md"
        label: "Navbar"
        name: "navbar"
        fields:
          - {
              label: "Layout Key",
              name: "layoutKey",
              widget: "hidden",
              default: "navbar",
            }
          - {
              label: "Menu Items",
              name: "menuItems",
              widget: "list",
              fields:
                [
                  { label: "Label", name: "label", widget: "string" },
                  {
                    label: "Link Type",
                    name: "linkType",
                    widget: "select",
                    options: ["internal", "external"],
                  },
                  {
                    label: "Link URL",
                    name: "linkURL",
                    widget: "string",
                    hint: "Use a relative URL (e.g. /about) if the link is an internal link.",
                  },
                ],
            }
      - file: "markdown/layout/footer.md"
        label: "Footer"
        name: "footer"
        fields:
          - {
              label: "Layout Key",
              name: "layoutKey",
              widget: "hidden",
              default: "footer",
            }
          - {
              label: "Logo Image & Tagline",
              name: "logoImage",
              widget: "object",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                  { label: "Tagline", name: "tagline", widget: "string" },
                ],
            }
          - {
              label: "Social Links",
              name: "socialLinks",
              widget: "list",
              fields:
                [
                  { label: "Image", name: "image", widget: "image" },
                  {
                    label: "Image Description",
                    name: "imageAlt",
                    widget: "string",
                  },
                  { label: "Label", name: "label", widget: "string" },
                  { label: "Link URL", name: "linkURL", widget: "string" },
                ],
            }
  - name: "lists"
    label: "Iterable items"
    description: "Any iterable list (cards, lists, gallery, links), needs to specify the pageKey and the listKey"
    folder: "markdown/lists"
    create: true
    fields:
      - { label: "Page Key", name: "pageKey", widget: "string" }
      - { label: "List Key", name: "listKey", widget: "string" }
      - {
          label: item,
          name: listItem,
          required: true,
          widget: list,
          fields:
            [
              { label: Title, name: text, required: false, widget: string },
              { label: Text, name: text, required: false, widget: string },
              { label: Image, name: image, required: false, widget: image },
              {
                label: Links,
                name: links,
                required: false,
                widget: list,
                fields:
                  [
                    {
                      label: Text,
                      name: linkText,
                      widget: string,
                      required: false,
                    },
                    {
                      label: URL,
                      name: linkURL,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            ],
        }
