backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "vocabulary"
    label: "Vocabulary"
    description: "Every copy or single word, needs a unique key (preferred kebab-case) and a pageKey"
    files:
      - file: "markdown/vocabulary/home.md"
        label: "Home page Vocabulary"
        name: "homeVocabulary"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "home",
            }

          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/chi-siamo.md"
        label: "Chi siamo page Vocabulary"
        name: "chiSiamoVocabulary"
        pageKey: "chi-siamo"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "chi-siamo",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/servizi.md"
        label: "Servizi page Vocabulary"
        name: "serviziVocabulary"
        pageKey: "servizi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "servizi",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/eventi.md"
        label: "Feste ed eventi page Vocabulary"
        name: "festeEdEventiVocabulary"
        pageKey: "eventi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "eventi",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/contattaci.md"
        label: "Contattaci page Vocabulary"
        name: "contattaciVocabulary"
        pageKey: "contattaci"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "contattaci",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
      - file: "markdown/vocabulary/la-struttura.md"
        label: "La struttura page Vocabulary"
        name: "lastrutturaVocabulary"
        pageKey: "la-struttura"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "la-struttura",
            }
          - {
              label: "Terms",
              name: "terms",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  { label: "Label", name: "label", widget: "string" },
                ],
            }
  - name: "gallery"
    label: "Images"
    description: "Every image, needs a unique key (preferred kebab-case) and a pageKey"
    files:
      - file: "markdown/gallery/home.md"
        label: "Home page Gallery"
        name: "homeGallery"
        pageKey: "home"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "home",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/chi-siamo.md"
        label: "Chi siamo page Gallery"
        name: "chiSiamoGallery"
        pageKey: "chi-siamo"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "chi-siamo",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/servizi.md"
        label: "Servizi page Gallery"
        name: "serviziGallery"
        pageKey: "servizi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "servizi",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/eventi.md"
        label: "Feste ed eventi page Gallery"
        name: "festeEdEventiGallery"
        pageKey: "eventi"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "eventi",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "markdown/gallery/la-struttura.md"
        label: "La struttura page Gallery"
        name: "lastrutturaGallery"
        pageKey: "la-struttura"
        fields:
          - {
              label: "Page Key",
              name: "pageKey",
              widget: "hidden",
              default: "la-struttura",
            }
          - {
              label: "Images",
              name: "images",
              widget: "list",
              fields:
                [
                  { label: "Key", name: "key", widget: "string" },
                  {
                    label: "Image description",
                    name: "description",
                    widget: "string",
                    required: false,
                  },
                  { label: Image, name: image, widget: image },
                ],
            }
  - name: "lists"
    label: "Iterable items"
    description: "Any iterable list (cards, lists, gallery, links), needs to specify the pageKey and the listKey"
    folder: "markdown/lists"
    create: true
    fields:
      - { label: "Page Key", name: "pageKey", widget: "string" }
      - { label: "List Key", name: "listKey", widget: "string" }
      - {
          label: item,
          name: listItem,
          required: true,
          widget: list,
          fields:
            [
              { label: Title, name: title, required: false, widget: string },
              { label: Text, name: text, required: false, widget: string },
              { label: Image, name: image, required: false, widget: image },
              {
                label: Links,
                name: links,
                required: false,
                widget: list,
                fields:
                  [
                    {
                      label: Text,
                      name: linkText,
                      widget: string,
                      required: false,
                    },
                    {
                      label: URL,
                      name: linkURL,
                      widget: string,
                      required: false,
                    },
                  ],
              },
            ],
        }
